apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicespecs.ha.example.com
spec:
  group: ha.example.com
  scope: Namespaced
  names:
    plural: servicespecs
    singular: servicespec
    kind: ServiceSpec
    shortNames:
      - svcspec
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
